CREATE TABLE detalle(
   id          	bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   filtro 		varchar,
   valor 		varchar not null,
   pvp    		double precision default null,
   stock       	bigint,
   unidad		varchar,
   producto_id	bigint not null,
   PRIMARY KEY (id)
);
