CREATE TABLE pedido(
   id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   codigo      varchar,
   fecha       timestamp without time zone,
   fecha_entrega       timestamp without time zone,
   qr          varchar,
   cantidad_qr double precision,
   total       double precision,
   generar     boolean,
   confirmar   boolean,
   enviado     boolean,
   pagado      boolean,
   cliente_id  bigint,
   PRIMARY KEY (id)
);
