CREATE TABLE producto(
   id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   descripcion varchar not null,
   material    varchar not null,
   marca       varchar not null,
   categoria   varchar not null,
   subcategoria	varchar not null,
   compra      double precision not null,
   precio      double precision not null,
   descuento   double precision,
   garantia    varchar not null,
   disponible  boolean,
   PRIMARY KEY (id)
);
